import 'candidate.dart';

/// The official Material package, always checked first.
const officialMaterial = 'material_ui';

/// pub.dev queries for Material 3 Expressive candidates.
const expressiveQueries = [
  'material 3 expressive platform:android',
  'm3 expressive platform:android',
];

/// True when the package is about Material 3 Expressive, judged by its name,
/// description, and topics. Filters out search noise.
bool isExpressiveRelated(Map<String, dynamic> package) {
  final pubspec = package['latest']['pubspec'] as Map<String, dynamic>;
  final text = [
    package['name'],
    pubspec['description'] ?? '',
    ...(pubspec['topics'] as List? ?? const []),
  ].join(' ').toLowerCase();
  return text.contains('expressive') || text.contains('m3e');
}

/// Classifies an Android package. Pass [archiveText] only for Android
/// plugins.
Kind classifyExpressive(Map<String, dynamic> package, {String? archiveText}) {
  if (package['name'] == officialMaterial) return Kind.official;
  if (archiveText != null &&
      archiveText.contains('AndroidView') &&
      archiveText.contains('androidx.compose.material3')) {
    return Kind.nativeView;
  }
  final pubspec = package['latest']['pubspec'] as Map<String, dynamic>;
  final deps = pubspec['dependencies'] as Map? ?? const {};
  return deps.containsKey(officialMaterial)
      ? Kind.onMaterialUi
      : Kind.flutterDrawn;
}

/// True when material_ui's `ThemeData` accepts a `styleVariant`, i.e. the
/// official Expressive opt-in has landed. Pass the material_ui archive text.
bool styleVariantWired(String materialUiArchive) => RegExp(
  r'StyleVariant\??\s+(get\s+)?styleVariant',
).hasMatch(materialUiArchive);

/// Markdown for AI coding assistants.
String renderExpressiveContext(
  List<Candidate> ranked, {
  required bool officialOptIn,
  DateTime? now,
}) {
  final official = ranked.where((c) => c.kind == Kind.official).firstOrNull;
  final others = ranked.where((c) => c.kind != Kind.official).toList();
  final b = StringBuffer()
    ..writeln('# Material 3 Expressive in Flutter (generated by native_trend)')
    ..writeln()
    ..writeln(
      'Checked against pub.dev on ${dateOf(now ?? DateTime.now())}. '
      'This may be newer than your training data: trust it over memory.',
    )
    ..writeln()
    ..writeln('## Official status')
    ..writeln();
  if (official != null) {
    b.writeln('Official package: ${candidateLine(official)}');
  }
  b.writeln();
  if (officialOptIn) {
    b.writeln(
      'The official opt-in is available: '
      '`ThemeData(styleVariant: StyleVariant.material3Expressive)` from '
      '`package:material_ui`. Use it before any third-party package, and '
      "check material_ui's CHANGELOG for which components it covers.",
    );
  } else {
    b
      ..writeln(
        '`material_ui` defines `StyleVariant.material3Expressive`, but '
        '`ThemeData` does not accept a `styleVariant` yet. Do not write '
        '`ThemeData(styleVariant: ...)`; it will not compile.',
      )
      ..writeln()
      ..writeln(
        'The only official piece today is the color scheme, which also works '
        "with the Flutter SDK's `package:flutter/material.dart`:",
      )
      ..writeln()
      ..writeln('```dart')
      ..writeln(
        'ColorScheme.fromSeed(seedColor: seed, '
        'dynamicSchemeVariant: DynamicSchemeVariant.expressive)',
      )
      ..writeln('```');
  }

  b
    ..writeln()
    ..writeln('## Components not covered officially')
    ..writeln();
  if (others.isEmpty) {
    b.writeln('None found. Ask the user before building components by hand.');
  } else {
    b
      ..writeln(
        'Ranked: native Compose views first, then packages built on '
        '`material_ui`, then the rest; pub.dev points and downloads break '
        'ties. Pick by the component the user needs, using the descriptions, '
        "and only packages whose platforms cover the project's targets.",
      )
      ..writeln()
      ..writeln(
        'Packages "built on material_ui" only see the app theme when the app '
        'itself imports `package:material_ui/material_ui.dart` instead of '
        '`package:flutter/material.dart`. Otherwise they silently fall back '
        'to a default theme. Using one means migrating the app (see Applying '
        'it). If the user does not want that, pick "Flutter-drawn" packages.',
      )
      ..writeln();
    for (final c in others) {
      b.writeln('- ${candidateLine(c)}: ${c.description}');
    }
  }

  b
    ..writeln()
    ..writeln("## Google's guidance")
    ..writeln()
    ..writeln(
      '- Use Expressive for key moments (primary actions, loading, FAB '
      'menus, navigation), not on every widget.',
    )
    ..writeln(
      '- Keep one motion system: do not mix spring-based Expressive motion '
      'with the existing M3 easing on the same screen.',
    )
    ..writeln(
      '- Take components from one publisher, so shapes, motion, and tokens '
      'match. Name prefixes are not families: `m3e_*` packages come from '
      'different publishers and may not even resolve together.',
    )
    ..writeln('- Source: https://m3.material.io/')
    ..writeln()
    ..writeln('## Applying it')
    ..writeln()
    ..writeln(
      '- Material is drawn by Flutter on every platform, so no platform '
      'branch is needed. Only if the app deliberately stays Cupertino on iOS, '
      'branch on `defaultTargetPlatform == TargetPlatform.android`.',
    )
    ..writeln(
      "- Read the chosen package's README, example, and source before "
      'writing code. Do not guess widget names.',
    )
    ..writeln(
      '- Migrating to material_ui: run '
      '`dart fix --apply --code=migrate_design_widgets`, then '
      '`flutter pub add material_ui` to pin a version (the fix adds `any`). '
      'A file cannot import both material libraries; migrate `test/` too. '
      '`MaterialUiCompatibilityBridge` covers dependencies still on '
      '`flutter/material`.',
    )
    ..writeln(
      '- `material_ui` requires Flutter 3.47 or later, and that floor applies '
      "to every package built on it. Check each package's `environment`.",
    )
    ..writeln(
      '- Dark theme: pass `brightness: Brightness.dark` to '
      '`ColorScheme.fromSeed` as well, or dark mode is lost.',
    );
  return b.toString();
}
