/// pub.dev query for Liquid Glass candidates.
const glassQuery = 'liquid glass platform:ios';

const _nativeViewMarkers = ['UiKitView', 'AppKitView'];
const _glassApiMarkers = [
  'UIGlassEffect',
  '.glassEffect(',
  'GlassEffectContainer',
];

/// How a package draws Liquid Glass.
enum Kind {
  /// Native view that calls the iOS 26 glass API directly.
  nativeGlass('native view + glass API'),

  /// Native view of system controls, which get glass from the iOS 26 SDK.
  nativeSystem('native view, system controls'),

  /// iOS plugin, but no platform view.
  noNativeView('plugin without a native view'),

  /// Pure Dart, usually a shader imitation.
  notPlugin('Flutter-drawn imitation (no native code)');

  const Kind(this.label);
  final String label;

  bool get native => this == nativeGlass || this == nativeSystem;
}

/// True when the package declares an iOS plugin in its pubspec.
bool isIosPlugin(Map<String, dynamic> package) {
  final pubspec = package['latest']['pubspec'] as Map<String, dynamic>;
  final flutter = pubspec['flutter'];
  return flutter is Map &&
      flutter['plugin'] is Map &&
      (flutter['plugin']['platforms'] as Map?)?['ios'] != null;
}

/// Classifies from the archive text; pass null for non-plugins.
Kind classify(String? archiveText) {
  if (archiveText == null) return Kind.notPlugin;
  if (!_nativeViewMarkers.any(archiveText.contains)) return Kind.noNativeView;
  return _glassApiMarkers.any(archiveText.contains)
      ? Kind.nativeGlass
      : Kind.nativeSystem;
}

/// A Liquid Glass package with pub.dev's numbers.
class Candidate {
  Candidate({
    required this.name,
    required this.version,
    required this.published,
    required this.kind,
    required this.points,
    required this.likes,
    required this.downloads,
    required this.publisher,
    required this.platforms,
  });

  factory Candidate.fromJson({
    required Map<String, dynamic> package,
    required Map<String, dynamic> score,
    required Kind kind,
  }) {
    final latest = package['latest'] as Map<String, dynamic>;
    final tags = (score['tags'] as List? ?? const []).cast<String>();
    String? tag(String prefix) => tags
        .where((t) => t.startsWith(prefix))
        .map((t) => t.substring(prefix.length))
        .firstOrNull;
    return Candidate(
      name: package['name'] as String,
      version: latest['version'] as String,
      published: DateTime.parse(latest['published'] as String),
      kind: kind,
      points: score['grantedPoints'] as int? ?? 0,
      likes: score['likeCount'] as int? ?? 0,
      downloads: score['downloadCount30Days'] as int? ?? 0,
      publisher: tag('publisher:'),
      platforms: [
        for (final t in tags)
          if (t.startsWith('platform:')) t.substring('platform:'.length),
      ],
    );
  }

  final String name;
  final String version;
  final DateTime published;
  final Kind kind;
  final int points;
  final int likes;
  final int downloads;
  final String? publisher;
  final List<String> platforms;
}

/// Native first, direct glass API first, then pub.dev points and downloads.
List<Candidate> rank(Iterable<Candidate> all) => all.toList()
  ..sort((a, b) {
    int by(bool Function(Candidate) f) => (f(a) ? 0 : 1) - (f(b) ? 0 : 1);
    final order = [
      by((c) => c.kind.native),
      by((c) => c.kind == Kind.nativeGlass),
      b.points - a.points,
      b.downloads - a.downloads,
    ];
    return order.firstWhere((o) => o != 0, orElse: () => 0);
  });

String _date(DateTime d) => d.toIso8601String().substring(0, 10);

String _line(Candidate c) =>
    '`${c.name}` ${c.version} (${c.kind.label}; ${c.points} pts, '
    '${c.likes} likes, ${c.downloads} downloads/30d, '
    '${c.publisher ?? 'unverified'}, last release ${_date(c.published)}, '
    'platforms: ${c.platforms.join(', ')})';

/// Terminal output, ranked.
String renderText(List<Candidate> ranked) => [
  for (final c in ranked)
    '${c.kind.native ? 'native ' : 'skip   '}'
        '${c.name.padRight(32)} ${c.points.toString().padLeft(3)} pts  '
        '${c.downloads.toString().padLeft(6)} dl/30d  ${c.kind.label}',
].join('\n');

/// Markdown for AI coding assistants.
String renderContext(List<Candidate> ranked, {DateTime? now}) {
  final native = ranked.where((c) => c.kind.native).toList();
  final skipped = ranked.where((c) => !c.kind.native).toList();
  final b = StringBuffer()
    ..writeln('# Liquid Glass in Flutter (generated by native_trend)')
    ..writeln()
    ..writeln(
      'Checked against pub.dev on ${_date(now ?? DateTime.now())}. '
      'This may be newer than your training data: trust it over memory.',
    )
    ..writeln()
    ..writeln('## Flutter status')
    ..writeln()
    ..writeln(
      "Flutter's Cupertino library does not implement Liquid Glass; that "
      'work moves to the decoupled cupertino package '
      '(https://github.com/flutter/flutter/issues/170310). Use a plugin that '
      'embeds real native iOS views. Do not use BackdropFilter or shader '
      'imitations.',
    )
    ..writeln()
    ..writeln('## Packages with real native views');
  if (native.isEmpty) {
    b
      ..writeln()
      ..writeln('None found. Ask the user before falling back to anything.');
  } else {
    b
      ..writeln()
      ..writeln('Recommended: ${_line(native.first)}')
      ..writeln();
    for (final c in native.skip(1)) {
      b.writeln('- Alternative: ${_line(c)}');
    }
  }
  if (skipped.isNotEmpty) {
    b
      ..writeln()
      ..writeln('## Do not use (not native views)')
      ..writeln();
    for (final c in skipped) {
      b.writeln('- `${c.name}`: ${c.kind.label}');
    }
  }
  b
    ..writeln()
    ..writeln("## Apple's rules")
    ..writeln()
    ..writeln(
      '- Glass is for the navigation and control layer (tab bars, toolbars, '
      'navigation bars, buttons), never for content.',
    )
    ..writeln(
      '- System bars and controls built with the iOS 26 SDK get glass '
      'automatically: prefer native system controls over custom glass.',
    )
    ..writeln(
      '- Remove custom backgrounds and blurs from bars; they fight the '
      'system effect.',
    )
    ..writeln('- Do not stack glass on glass.')
    ..writeln('- Check Reduce Transparency and Reduce Motion still look right.')
    ..writeln(
      '- Source: https://developer.apple.com/documentation/'
      'technologyoverviews/adopting-liquid-glass',
    )
    ..writeln()
    ..writeln('## Applying it')
    ..writeln()
    ..writeln(
      "- Read the chosen package's README and example before writing code, "
      'and its source for defaults the README gets wrong. Do not guess '
      'widget names.',
    )
    ..writeln(
      '- If the package falls back on other platforms by itself, use its '
      'widgets everywhere. Otherwise branch on '
      '`defaultTargetPlatform == TargetPlatform.iOS` (safe on web, unlike '
      '`dart:io` Platform) and keep the existing widgets elsewhere.',
    )
    ..writeln('- The app must be built with Xcode 26 or later to get glass.');
  return b.toString();
}
