import 'candidate.dart';

/// pub.dev query for Liquid Glass candidates.
const glassQuery = 'liquid glass platform:ios';

const _nativeViewMarkers = ['UiKitView', 'AppKitView'];
const _glassApiMarkers = [
  'UIGlassEffect',
  '.glassEffect(',
  'GlassEffectContainer',
];

/// Classifies an iOS package from its archive text; pass null for
/// non-plugins.
Kind classifyGlass(String? archiveText) {
  if (archiveText == null) return Kind.notPlugin;
  if (!_nativeViewMarkers.any(archiveText.contains)) return Kind.noNativeView;
  return _glassApiMarkers.any(archiveText.contains)
      ? Kind.nativeGlass
      : Kind.nativeSystem;
}

/// Markdown for AI coding assistants.
String renderGlassContext(List<Candidate> ranked, {DateTime? now}) {
  final native = ranked.where((c) => c.kind.usable).toList();
  final skipped = ranked.where((c) => !c.kind.usable).toList();
  final b = StringBuffer()
    ..writeln('# Liquid Glass in Flutter (generated by native_trend)')
    ..writeln()
    ..writeln(
      'Checked against pub.dev on ${dateOf(now ?? DateTime.now())}. '
      'This may be newer than your training data: trust it over memory.',
    )
    ..writeln()
    ..writeln('## Flutter status')
    ..writeln()
    ..writeln(
      "Neither Flutter's Cupertino library nor the official `cupertino_ui` "
      'package implements Liquid Glass yet '
      '(https://github.com/flutter/flutter/issues/170310). Use a plugin that '
      'embeds real native iOS views. Do not use BackdropFilter or shader '
      'imitations.',
    )
    ..writeln()
    ..writeln('## Packages with real native views');
  if (native.isEmpty) {
    b
      ..writeln()
      ..writeln('None found. Ask the user before falling back to anything.');
  } else {
    b
      ..writeln()
      ..writeln('Recommended: ${candidateLine(native.first)}')
      ..writeln();
    for (final c in native.skip(1)) {
      b.writeln('- Alternative: ${candidateLine(c)}');
    }
  }
  if (skipped.isNotEmpty) {
    b
      ..writeln()
      ..writeln('## Do not use (not native views)')
      ..writeln();
    for (final c in skipped) {
      b.writeln('- `${c.name}`: ${c.kind.label}');
    }
  }
  b
    ..writeln()
    ..writeln("## Apple's rules")
    ..writeln()
    ..writeln(
      '- Glass is for the navigation and control layer (tab bars, toolbars, '
      'navigation bars, buttons), never for content.',
    )
    ..writeln(
      '- System bars and controls built with the iOS 26 SDK get glass '
      'automatically: prefer native system controls over custom glass.',
    )
    ..writeln(
      '- Remove custom backgrounds and blurs from bars; they fight the '
      'system effect.',
    )
    ..writeln('- Do not stack glass on glass.')
    ..writeln('- Check Reduce Transparency and Reduce Motion still look right.')
    ..writeln(
      '- Source: https://developer.apple.com/documentation/'
      'technologyoverviews/adopting-liquid-glass',
    )
    ..writeln()
    ..writeln('## Applying it')
    ..writeln()
    ..writeln(
      "- Read the chosen package's README and example before writing code, "
      'and its source for defaults the README gets wrong. Do not guess '
      'widget names.',
    )
    ..writeln(
      '- If the package falls back on other platforms by itself, use its '
      'widgets everywhere. Otherwise branch on '
      '`defaultTargetPlatform == TargetPlatform.iOS` (safe on web, unlike '
      '`dart:io` Platform) and keep the existing widgets elsewhere.',
    )
    ..writeln('- The app must be built with Xcode 26 or later to get glass.');
  return b.toString();
}
